
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2.4.0
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm ci

    - name: Run TypeScript Check
      run: npm run check